# Generated by Django 2.0.4 on 2018-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('pass_word', models.CharField(max_length=20, verbose_name='密码')),
                ('user_phone', models.CharField(max_length=15, verbose_name='手机号码')),
                ('car_number', models.CharField(max_length=11, verbose_name='车牌号')),
                ('car_type', models.CharField(max_length=11, verbose_name='车型')),
                ('car_color', models.CharField(max_length=8, verbose_name='车色')),
                ('car_kind', models.CharField(max_length=8, verbose_name='车种')),
                ('balance', models.IntegerField(verbose_name='余额')),
            ],
        ),
    ]
