# Generated by Django 2.0.4 on 2018-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(verbose_name='余额'),
        ),
    ]
