# Generated by Django 2.0.5 on 2018-05-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180506_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pass_word',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_name',
        ),
    ]
