# Generated by Django 2.0.5 on 2018-05-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carposition',
            name='position_num',
            field=models.CharField(default='None', max_length=20, verbose_name='车位编号'),
        ),
        migrations.AlterField(
            model_name='carposition',
            name='position_status',
            field=models.BooleanField(default=True, verbose_name='车位状态[默认为空闲]'),
        ),
    ]
