# Generated by Django 2.0.5 on 2018-05-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carposition', '0002_auto_20180514_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carposition',
            options={'verbose_name': '车位', 'verbose_name_plural': '车位'},
        ),
    ]
