# Generated by Django 2.0.5 on 2018-05-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_auto_20180514_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='parking_money',
            field=models.FloatField(default=0.0, editable=False, verbose_name='停车费'),
        ),
    ]
